# Generated by Django 3.0.6 on 2020-06-03 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Title')),
                ('type', models.CharField(choices=[('Updates', (('UA', 'Added'), ('UF', 'Fixed'), ('UR', 'Removed'), ('UC', 'Changelog'))), ('Server', (('SM', 'Maintenance'),))], max_length=2, verbose_name='Type')),
                ('content', models.TextField(verbose_name='Content')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
