# Generated by Django 3.0.6 on 2020-05-31 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('decks', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='deck',
            options={'ordering': ['-pk']},
        ),
    ]
