# Generated by Django 3.0.6 on 2020-05-31 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('decks', '0002_auto_20200531_1402'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='deck',
            options={'ordering': ['-official', '-pk']},
        ),
        migrations.AddField(
            model_name='deck',
            name='official',
            field=models.BooleanField(default=False, verbose_name='Official'),
        ),
    ]
