# Generated by Django 3.0.6 on 2020-06-01 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('decks', '0003_auto_20200531_1751'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blackcard',
            name='text',
            field=models.TextField(max_length=64, verbose_name='Text'),
        ),
        migrations.AlterField(
            model_name='whitecard',
            name='text',
            field=models.TextField(max_length=64, verbose_name='Text'),
        ),
    ]
