# Generated by Django 3.0.6 on 2020-06-02 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('decks', '0005_update_blackcard_blanks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blackcard',
            name='text',
            field=models.TextField(max_length=128, verbose_name='Text'),
        ),
        migrations.AlterField(
            model_name='whitecard',
            name='text',
            field=models.TextField(max_length=128, verbose_name='Text'),
        ),
    ]
